Vector Templates
DmitryZakhar0v/ProgrammingVectorTemplates pull request #1
Opened 2023-10-17 15:17 UTC by DmitryZakhar0v

2023-10-29 15:09 UTC, MarinaPaley requested changes

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		int get_size() const;
`size_t`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		void append(T value);
`const T&`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		int find(T value) const;
`size_t find(const T& value) const;`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		T& operator[](int index);
`const size_t index`
`const T& operator(const size_t index) const`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		:size(0)
`size{list.size}`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		for (int value : list)
`for (auto value...`
int != T !!!!!!

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		this->size++;
Я планировала показать на лекции более безопасный вариант!

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		std::swap(vector.values, this->values);
`if (this != *other)
{....}
return *this;`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		}
Это тоже можно переделать. На лекции должна показать как.

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		}
Нужно проверять на неравенство `a = a`.

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		if (this->size == 0 or index < 0 or index >= this->size)
Неконсистентность `or` и `||`

2023-10-29 15:09 UTC, MarinaPaley commented on Vector/Vector.h
> +		void pop(int index);
`size_t`
только, это же вектор, зачем `pop`?

2023-11-05 12:54 UTC, DmitryZakhar0v commented on Vector/Vector.h
> +		:size(0)
Вектор при создании заполняется с помощью метода append, в этом методе предусмотрено увеличение размера, поэтому в начале размер равен 0

2023-11-10 07:20 UTC, MarinaPaley commented on Vector/Vector.h
> +		:size(0)
да, я понимаю, но зачем?

2023-11-13 08:33 UTC, MarinaPaley requested changes
Очень неплохо
тесты видела, к ним придирки

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		@return Объект типа DLList
Ну, нет(

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		@param vector Вектор для мува
документация должна помогать!!! какой мув)?

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		for (int value : list)
Не все ошибки исправлены

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		this->size++;
Я его показала уже!!!
[Идиома copy and swap](https://ru.wikipedia.org/wiki/Copy-and-swap#:~:text=Идиома_copy-and-swap—,«Получение_ресурса_есть_инициализация».)

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		if (this->has_elements())
[Идиома copy and swap](https://ru.wikipedia.org/wiki/Copy-and-swap#:~:text=Идиома_copy-and-swap—,«Получение_ресурса_есть_инициализация».)

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		std::swap(vector.size, this->size);
`*this = other;`

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +
Одна строка для пропуска, для читаемости

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +			if (this->has_elements())
[Идиома copy and swap](https://ru.wikipedia.org/wiki/Copy-and-swap#:~:text=Идиома_copy-and-swap—,«Получение_ресурса_есть_инициализация».)

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +			return -1;
Не подходит такое решение, так как возвращает `size_t`. Или возвращайте `int`, или придумайте другой подход.

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +	}
Надо проще... что-то тяжело

2023-11-13 08:33 UTC, MarinaPaley commented on Vector/Vector.h
> +		if (!this->has_elements() || index >= this->size or index < 0)
Для беззнакового числа проверка на отрицательное значение не имеет смысла.
![image](https://github.com/DmitryZakhar0v/ProgrammingVectorTemplates/assets/26978698/b8134672-fbc6-439f-a1fd-d469f0195cd3)

2023-11-21 07:54 UTC, MarinaPaley requested changes

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
> +		for (auto value : list)
`auto&`

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
> +		T* new_values = new T[this->size + 1];
1. Ваш способ, когда каждый раз при добавлении элемента, размер увеличивается на единицу, неэффективен. Лучше увеличивать размер в два раза (проведены исследования)
2. Используйте идиому [`copy and swap`](https://ru.wikipedia.org/wiki/Copy-and-swap)

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
> +	{
У Вас дублирование кода. Поэтому в конструкторе перемещения можно сделать так
`*this = std::move(other);` (Вызываете оператор присваивания)

Строка конструктора копирования (не указала в прошлый раз - в этот нет возможности указать ошибку). Ваш код:
```cpp
template<typename T
Vector<T>::Vector(const Vector<T>& vector)
		:size(0), values(nullptr)	
	{
		if (this->has_elements())			
		{	...}
```
Это конструктор, объекта `this` пока не существует, будет после выхода из конструктора.
Соответственно, никакой проверки на содержание делать не нужно, сразу добавляйте элементы. (Мне НЕ нравится Ваше решение с возможностью отрицательного индекса).

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
>  		@param Vector Список для мува
А здесь?

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
> +		int find(const T& value) const;
Почему не сделать `bool`. И тогда отпадет возможность в костылях). Будете всегда использовать `size_t` для индексации и размера.

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
>  	{
Можно так (если будет индексация в `size_t`) `index >= this->size`

2023-11-21 07:54 UTC, MarinaPaley commented on Vector/Vector.h
>  	template<typename T>
используйте идиому copy & swap

2023-11-27 16:40 UTC, MarinaPaley requested changes

2023-11-27 16:40 UTC, MarinaPaley commented on Vector/Vector.h
>  	inline Vector<T>::Vector(const std::initializer_list<T> list)
`const` не нужен

2023-11-27 16:40 UTC, MarinaPaley commented on Vector/Vector.h
>  	{
Только это `*this = std::move(other);`

2023-11-27 16:40 UTC, MarinaPaley commented on Vector/Vector.h
>  		for (int i = 0; i < vector.get_size(); i++)
`size_t`

2023-11-27 16:40 UTC, MarinaPaley commented on Vector/Vector.h
> +			Vector temp{};
```cpp
Vector temp{vector}; // вызов конструктора копирования
std::swap(this->values, temp.values);
std::exchange(this->size, temp.size); //вчера собирала под Линукс, там swap не идет для `size_t`

2023-11-29 09:00 UTC, MarinaPaley approved these changes

2023-11-29 09:10 UTC, merged